let shopItemsData = [{
    id:"gftfvgh",
    name:"Casual Shirt",
    price: 45,
    desc:"Very comfortable casual light green shirt.",
    img: "images/img-1.jpg",
},
{
    id:"gfvgh",
    name:"Office Shirt",
    price: 100,
    desc:"Very well fit Office shirt and get impressed by wearing.",
    img: "images/img-2.jpg",

},
{
    id:"gbhcbc",
    name:"T Shirt",
    price: 25,
    desc:"Very free and causal and style looking white T shirt.",
    img: "images/img-3.jpg",

},
{
    id:"gnijcnh",
    name:"Mens Suit",
    price: 300,
    desc:"Well formal best suit for mens, free to fit.",
    img: "images/img-4.jpg",
},
{
    id: "thiecbawdjksadjk",
    name: "Mens Tie",
    price: 25,
    desc: "Well suited blue Tie for a formal wear suit.",
    img: "images/img-5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Casual shoes",
    price: 200,
    desc: "Casual and good looking daily wear shoes.",
    img: "images/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "black suit",
    price: 450,
    desc: "A black suit which attracts everyone around you. ",
    img: "images/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "polo shirt",
    price: 45,
    desc: "Well branded polo shirt which is of navy blue colour.",
    img: "images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "denim shirt",
    price: 85,
    desc: "A branded denim blue shirt",
    img: "images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "denim pants",
    price: 120,
    desc: "Denim pants of black and blue colour which suits on almost every shirt.",
    img: "images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "basic cap",
    price: 35,
    desc: "Sometimes try to put on a cap which makes you unique,so here is a black cap.",
    img: "images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "leather boots",
    price: 350,
    desc: "An outfit without shoes is weird , Here is the leather boots.",
    img: "images/img-12.png",
  },
];